[netconfig]
# Server will listen for clients on this port
ip = "127.0.0.1:1234"
# Server will bind [client_addr]:read_port and will use this
# connection for reading data from the client
read_port = 4321

[systemconfig]
# Amount of threads that will be given to the server
threads = 20
# The number the keys assigned to clients will start at
key_start = 0
# Tells you the secrets to life
verbose = true
